<?xml version="1.0"?>
<package format="3">
  <name>eup_mujoco_env</name>
  <version>0.1.0</version>
  <description>MuJoCo backend package for EUPSystemInfraPack.</description>
  <maintainer email="maintainer@example.com">EUP System Team</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>eup_interfaces</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>rosgraph_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
