thrusters:
  count: 8
  action_min: -1.0
  action_max: 1.0
  pwm_neutral_us: 1500
  action_pwm_span_us: 250
  layout:
    - {id: 0, name: right_front_vertical_down_positive, frame: base_link}
    - {id: 1, name: right_rear_vertical_down_positive, frame: base_link}
    - {id: 2, name: left_front_vertical_down_positive, frame: base_link}
    - {id: 3, name: left_rear_vertical_down_positive, frame: base_link}
    - {id: 4, name: left_rear_horizontal, frame: base_link}
    - {id: 5, name: right_rear_horizontal, frame: base_link}
    - {id: 6, name: left_front_horizontal, frame: base_link}
    - {id: 7, name: right_front_horizontal, frame: base_link}
