<?xml version="1.0"?>
<package format="3">
  <name>robotcore_hardware</name>
  <version>0.1.0</version>
  <description>Edge hardware bridge skeleton for ros2_control, serial, CAN, and Aboard packets.</description>
  <maintainer email="maintainer@example.com">RobotCore Team</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>boost</depend>
  <depend>diagnostic_updater</depend>
  <depend>diagnostic_msgs</depend>
  <depend>robotcore_interfaces</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
